name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN }}
          base: header
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_padding: 2, 8 + 11%
  
  metric:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRIC_TOKEN }}
          base: repo
          plugin_languages: yes
          plugin_languages_threshold: 2%
          plugin_languages_ignored: >-
            html, css, dockerfile, makefile, shell, java
          plugin_languages_sections: recently-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 4
          config_display: large
          config_order: base.header, base.repo 
          
          

